function about() {
$('.nav-wrapper div.header').html('API Documentation | About');
        $('div#index-banner div.container').html('<h3>AJAX Requests structure</h3><em><u>One-off Procedure for first time use:</u><br/>Login to <a href="http://group-notification-mechanism.appspot.com" target="_blank">Group Notification Mechanism</a> using the Google account that your service will use and grant access to specified scopes!</em><blockquote>All AJAX requests have the following structure</blockquote><div style="background-color: lightgray;"><code>var <em>JSON_VAR</em> = {<br/><em>JSON_KEY_1</em>: <em>JSON_VALUE_1</em>,<br/><em>JSON_KEY_2</em>: <em>JSON_VALUE_2</em>,<br/>.<br/>.<br/>.<br/>};<br/><br/>$.post("<em>SERVLET_NAME</em>", {json: <em>JSON_VAR</em>}, function (response, statusText, xhr) {<br/>}<br/>});</code></div><br/><em style="color: black;">Before start using the API calls first you should auhenticate user with google and then follow <a onclick="authentication();">these</a> steps.</em>');
}

function authentication() {
$('li').removeClass("active");
        $('li#auth').addClass("active");
        $('.nav-wrapper div.header').html('API Documentation | Authentication');
        $('div#index-banner div.container').html('<h3>User Authentication</h3><br/><table class="responsive-table striped"><thead><tr><th data-field="JSON KEY">JSON KEY</th><th data-field="TYPE">TYPE</th><th data-field="VALUE">VALUE</th><th data-field="DESCRIPTION">DESCRIPTION</th></tr></thead><tbody><tr><td>auth_code</td><td>String</td><td>String</td><td>Google Auth code</td></tr><tr><td>user_email</td><td>String</td><td>User\'s email</td><td>Authenticated user\'s email</td></tr></tbody></table>');
}

function addSchemeAPI() {
$('.nav-wrapper div.header').html('API Documentation | Manage Schemes > Add');
        $('div#index-banner div.container').html('<h3>Add new Scheme</h3><br/><table class="responsive-table striped"> <thead> <tr> <th data-field="JSON KEY">JSON KEY</th> <th data-field="TYPE">TYPE</th> <th data-field="VALUE">VALUE</th> <th data-field="DESCRIPTION">DESCRIPTION</th> </tr> </thead> <tbody> <tr> <td>id</td> <td>String</td> <td>0</td> <td>UUID of scheme</td> </tr> <tr> <td>eventId</td> <td>String</td> <td>0 if does not exists</td> <td>If new scheme is created by a suggestion event from Google Calendar provide the id of the event</td> </tr> <tr> <td>user_email</td> <td>String</td> <td>User\'s email</td> <td>Authenticated user\'s email</td> </tr> <tr> <td>contacts</td> <td>String</td> <td>Comma (,) separated email addresses with no spaces</td> <td>Scheme recipients and event guests if new scheme is created by a suggestion event from Google Calendar</td> </tr> <tr> <td>subject</td> <td>String</td> <td>String</td> <td>Notification\'s subject</td> </tr> <tr> <td>message</td> <td>String</td> <td>Can be html</td> <td>Notification\'s message</td> </tr> <tr> <td>now</td> <td>String</td> <td>true or false</td> <td>If true notification is sent instantly</td> </tr> <tr> <td>calendarId</td> <td>String</td> <td>0</td> <td>If not 0 a new event is created in the preffered calendar and associated with the new scheme. Use the word \'primary\' for primary calendar</td> </tr> <tr> <td>date</td> <td>String</td> <td>yyyy-MM-dd</td> <td>Date to send the notification. If now is true date must be current date</td> </tr> <tr> <td>time</td> <td>String</td> <td>HH:mm</td> <td>Time to send the notification. If now is true time must be current time</td> </tr> <tr> <td>eventStart</td> <td>String</td> <td>yyyy-MM-dd HH:mm</td> <td>If a new event is about to be created provide when the event will start</td> </tr> <tr> <td>eventEnd</td> <td>String</td> <td>yyyy-MM-dd HH:mm</td> <td>If a new event is about to be created provide when the event will end</td> </tr> <tr> <td>timeZoneOffset</td> <td>String</td> <td>+HH or -HH</td> <td>Local timezone offset hours +HH or -HH</td> </tr> <tr> <td>type</td> <td>String</td> <td>ADD</td> <td>Default type to add a new Notification Scheme</td> </tr> </tbody> </table>');
}

function deleteSchemeAPI() {
$('.nav-wrapper div.header').html('API Documentation | Manage Schemes > Delete');
        $('div#index-banner div.container').html('<h3>Delete a Scheme</h3> <br/> <table class="responsive-table striped"> <thead> <tr> <th data-field="JSON KEY">JSON KEY</th> <th data-field="TYPE">TYPE</th> <th data-field="VALUE">VALUE</th> <th data-field="DESCRIPTION">DESCRIPTION</th> </tr> </thead> <tbody> <tr> <td>id</td> <td>String</td> <td>Scheme\'s UUID</td> <td>UUID of the scheme to delete</td> </tr> <tr> <td>user_email</td> <td>String</td> <td>User\'s email</td> <td>Authenticated user\'s email</td> </tr> <tr> <td>type</td> <td>String</td> <td>DELETE</td> <td>Default type to delete a Notification Scheme</td> </tr> </tbody> </table>');
}

function updateSchemeAPI() {
$('.nav-wrapper div.header').html('API Documentation | Manage Schemes > Update');
        $('div#index-banner div.container').html('<h3>Update a Scheme</h3> <br/><table class="responsive-table striped"> <thead> <tr> <th data-field="JSON KEY">JSON KEY</th> <th data-field="TYPE">TYPE</th> <th data-field="VALUE">VALUE</th> <th data-field="DESCRIPTION">DESCRIPTION</th> </tr> </thead> <tbody> <tr> <td>id</td> <td>String</td> <td>Scheme\'s UUID</td> <td>UUID of scheme to be updated</td> </tr> <tr> <td>eventId</td> <td>String</td> <td>0 if does not exists</td> <td>If new scheme is created by a suggestion event from Google Calendar provide the id of the event</td> </tr> <tr> <td>user_email</td> <td>String</td> <td>User\'s email</td> <td>Authenticated user\'s email</td> </tr> <tr> <td>contacts</td> <td>String</td> <td>Comma (,) separated email addresses with no spaces</td> <td>Scheme recipients and event guests if new scheme is created by a suggestion event from Google Calendar</td> </tr> <tr> <td>subject</td> <td>String</td> <td>String</td> <td>Notification\'s subject</td> </tr> <tr> <td>message</td> <td>String</td> <td>Can be html</td> <td>Notification\'s message</td> </tr> <tr> <td>now</td> <td>String</td> <td>true or false</td> <td>If true notification is sent instantly</td> </tr> <tr> <td>calendarId</td> <td>String</td> <td>0</td> <td>If not 0 a new event is created in the preffered calendar and associated with the new scheme. Use the word \'primary\' for primary calendar</td> </tr> <tr> <td>date</td> <td>String</td> <td>yyyy-MM-dd</td> <td>Date to send the notification. If now is true date must be current date</td> </tr> <tr> <td>time</td> <td>String</td> <td>HH:mm</td> <td>Time to send the notification. If now is true time must be current time</td> </tr> <tr> <td>eventStart</td> <td>String</td> <td>yyyy-MM-dd HH:mm</td> <td>If a new event is about to be created provide when the event will start</td> </tr> <tr> <td>eventEnd</td> <td>String</td> <td>yyyy-MM-dd HH:mm</td> <td>If a new event is about to be created provide when the event will end</td> </tr> <tr> <td>timeZoneOffset</td> <td>String</td> <td>+HH or -HH</td> <td>Local timezone offset hours +HH or -HH</td> </tr> <tr> <td>owner</td> <td>String</td> <td>0 or 1 or 2</td> <td>If 0 updates only Notification Scheme. If 1 updates Notificzation Scheme and associated event (if authorized user has the proper rights) and if 2 an event is created and associated with the scheme</td> </tr> <tr> <td>type</td> <td>String</td> <td>ADD</td> <td>Default type to add a new Notification Scheme</td> </tr> </tbody> </table>');
}

function copySchemeAPI() {
$('.nav-wrapper div.header').html('API Documentation | Manage Schemes > Copy');
        $('div#index-banner div.container').html('<h3>Copy a Scheme</h3> <br/><table class="responsive-table striped"> <thead> <tr> <th data-field="JSON KEY">JSON KEY</th> <th data-field="TYPE">TYPE</th> <th data-field="VALUE">VALUE</th> <th data-field="DESCRIPTION">DESCRIPTION</th> </tr> </thead> <tbody> <tr> <td>id</td> <td>String</td> <td>Scheme\'s UUID</td> <td>UUID of scheme to copy</td> </tr> <tr> <td>user_email</td> <td>String</td> <td>User\'s email</td> <td>Authenticated user\'s email</td> </tr> <tr> <td>contacts</td> <td>String</td> <td>Comma (,) separated email addresses with no spaces</td> <td>Scheme recipients and event guests if new scheme is created by a suggestion event from Google Calendar</td> </tr> <tr> <td>subject</td> <td>String</td> <td>String</td> <td>Notification\'s subject</td> </tr> <tr> <td>message</td> <td>String</td> <td>Can be html</td> <td>Notification\'s message</td> </tr> <tr> <td>now</td> <td>String</td> <td>true or false</td> <td>If true notification is sent instantly</td> </tr> <tr> <td>date</td> <td>String</td> <td>yyyy-MM-dd</td> <td>Date to send the notification. If now is true date must be current date</td> </tr> <tr> <td>time</td> <td>String</td> <td>HH:mm</td> <td>Time to send the notification. If now is true time must be current time</td> </tr> <tr> <td>type</td> <td>String</td> <td>COPY</td> <td>Default type to copy a Notification Scheme</td> </tr> </tbody> </table>');
}